(cl:defpackage beginner_tutorials-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "AREARECT"
   "<AREARECT-REQUEST>"
   "AREARECT-REQUEST"
   "<AREARECT-RESPONSE>"
   "AREARECT-RESPONSE"
  ))

