// Generated by gencpp from file beginner_tutorials/AreaRectResponse.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_AREARECTRESPONSE_H
#define BEGINNER_TUTORIALS_MESSAGE_AREARECTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct AreaRectResponse_
{
  typedef AreaRectResponse_<ContainerAllocator> Type;

  AreaRectResponse_()
    : area(0.0)  {
    }
  AreaRectResponse_(const ContainerAllocator& _alloc)
    : area(0.0)  {
  (void)_alloc;
    }



   typedef float _area_type;
  _area_type area;





  typedef boost::shared_ptr< ::beginner_tutorials::AreaRectResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::AreaRectResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AreaRectResponse_

typedef ::beginner_tutorials::AreaRectResponse_<std::allocator<void> > AreaRectResponse;

typedef boost::shared_ptr< ::beginner_tutorials::AreaRectResponse > AreaRectResponsePtr;
typedef boost::shared_ptr< ::beginner_tutorials::AreaRectResponse const> AreaRectResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::AreaRectResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::AreaRectResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::AreaRectResponse_<ContainerAllocator1> & lhs, const ::beginner_tutorials::AreaRectResponse_<ContainerAllocator2> & rhs)
{
  return lhs.area == rhs.area;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::AreaRectResponse_<ContainerAllocator1> & lhs, const ::beginner_tutorials::AreaRectResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::AreaRectResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::AreaRectResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::AreaRectResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::AreaRectResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::AreaRectResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::AreaRectResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::AreaRectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba46cd039de682077b3eaa09c3500c5c";
  }

  static const char* value(const ::beginner_tutorials::AreaRectResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba46cd039de68207ULL;
  static const uint64_t static_value2 = 0x7b3eaa09c3500c5cULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::AreaRectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/AreaRectResponse";
  }

  static const char* value(const ::beginner_tutorials::AreaRectResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::AreaRectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 area\n"
;
  }

  static const char* value(const ::beginner_tutorials::AreaRectResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::AreaRectResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.area);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AreaRectResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::AreaRectResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::AreaRectResponse_<ContainerAllocator>& v)
  {
    s << indent << "area: ";
    Printer<float>::stream(s, indent + "  ", v.area);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_AREARECTRESPONSE_H
