// Generated by gencpp from file beginner_tutorials/AreaRect.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_AREARECT_H
#define BEGINNER_TUTORIALS_MESSAGE_AREARECT_H

#include <ros/service_traits.h>


#include <beginner_tutorials/AreaRectRequest.h>
#include <beginner_tutorials/AreaRectResponse.h>


namespace beginner_tutorials
{

struct AreaRect
{

typedef AreaRectRequest Request;
typedef AreaRectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AreaRect
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::AreaRect > {
  static const char* value()
  {
    return "776367f335c9bf437d261b53f116f71c";
  }

  static const char* value(const ::beginner_tutorials::AreaRect&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::AreaRect > {
  static const char* value()
  {
    return "beginner_tutorials/AreaRect";
  }

  static const char* value(const ::beginner_tutorials::AreaRect&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::AreaRectRequest> should match
// service_traits::MD5Sum< ::beginner_tutorials::AreaRect >
template<>
struct MD5Sum< ::beginner_tutorials::AreaRectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::AreaRect >::value();
  }
  static const char* value(const ::beginner_tutorials::AreaRectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::AreaRectRequest> should match
// service_traits::DataType< ::beginner_tutorials::AreaRect >
template<>
struct DataType< ::beginner_tutorials::AreaRectRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::AreaRect >::value();
  }
  static const char* value(const ::beginner_tutorials::AreaRectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::AreaRectResponse> should match
// service_traits::MD5Sum< ::beginner_tutorials::AreaRect >
template<>
struct MD5Sum< ::beginner_tutorials::AreaRectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::AreaRect >::value();
  }
  static const char* value(const ::beginner_tutorials::AreaRectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::AreaRectResponse> should match
// service_traits::DataType< ::beginner_tutorials::AreaRect >
template<>
struct DataType< ::beginner_tutorials::AreaRectResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::AreaRect >::value();
  }
  static const char* value(const ::beginner_tutorials::AreaRectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_AREARECT_H
