// Generated by gencpp from file beginner_tutorials/Eli.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_ELI_H
#define BEGINNER_TUTORIALS_MESSAGE_ELI_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct Eli_
{
  typedef Eli_<ContainerAllocator> Type;

  Eli_()
    : name()
    , eli()  {
    }
  Eli_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , eli(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _eli_type;
  _eli_type eli;





  typedef boost::shared_ptr< ::beginner_tutorials::Eli_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::Eli_<ContainerAllocator> const> ConstPtr;

}; // struct Eli_

typedef ::beginner_tutorials::Eli_<std::allocator<void> > Eli;

typedef boost::shared_ptr< ::beginner_tutorials::Eli > EliPtr;
typedef boost::shared_ptr< ::beginner_tutorials::Eli const> EliConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::Eli_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::Eli_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::Eli_<ContainerAllocator1> & lhs, const ::beginner_tutorials::Eli_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.eli == rhs.eli;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::Eli_<ContainerAllocator1> & lhs, const ::beginner_tutorials::Eli_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::Eli_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::Eli_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::Eli_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::Eli_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::Eli_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::Eli_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::Eli_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ec098ac8c9a478cf0c042931a2dbdf90";
  }

  static const char* value(const ::beginner_tutorials::Eli_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xec098ac8c9a478cfULL;
  static const uint64_t static_value2 = 0x0c042931a2dbdf90ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::Eli_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/Eli";
  }

  static const char* value(const ::beginner_tutorials::Eli_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::Eli_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"string eli\n"
;
  }

  static const char* value(const ::beginner_tutorials::Eli_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::Eli_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.eli);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Eli_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::Eli_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::Eli_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "eli: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.eli);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_ELI_H
