// Generated by gencpp from file beginner_tutorials/hello.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_HELLO_H
#define BEGINNER_TUTORIALS_MESSAGE_HELLO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct hello_
{
  typedef hello_<ContainerAllocator> Type;

  hello_()
    : helloo()  {
    }
  hello_(const ContainerAllocator& _alloc)
    : helloo(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _helloo_type;
  _helloo_type helloo;





  typedef boost::shared_ptr< ::beginner_tutorials::hello_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::hello_<ContainerAllocator> const> ConstPtr;

}; // struct hello_

typedef ::beginner_tutorials::hello_<std::allocator<void> > hello;

typedef boost::shared_ptr< ::beginner_tutorials::hello > helloPtr;
typedef boost::shared_ptr< ::beginner_tutorials::hello const> helloConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::hello_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::hello_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::hello_<ContainerAllocator1> & lhs, const ::beginner_tutorials::hello_<ContainerAllocator2> & rhs)
{
  return lhs.helloo == rhs.helloo;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::hello_<ContainerAllocator1> & lhs, const ::beginner_tutorials::hello_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::hello_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::hello_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::hello_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::hello_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::hello_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::hello_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::hello_<ContainerAllocator> >
{
  static const char* value()
  {
    return "79c61f44b47be5109868ef063497ba56";
  }

  static const char* value(const ::beginner_tutorials::hello_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x79c61f44b47be510ULL;
  static const uint64_t static_value2 = 0x9868ef063497ba56ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::hello_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/hello";
  }

  static const char* value(const ::beginner_tutorials::hello_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::hello_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string helloo\n"
;
  }

  static const char* value(const ::beginner_tutorials::hello_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::hello_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.helloo);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct hello_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::hello_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::hello_<ContainerAllocator>& v)
  {
    s << indent << "helloo: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.helloo);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_HELLO_H
