// Generated by gencpp from file beginner_tutorials/Person.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_PERSON_H
#define BEGINNER_TUTORIALS_MESSAGE_PERSON_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct Person_
{
  typedef Person_<ContainerAllocator> Type;

  Person_()
    : age(0)
    , name()  {
    }
  Person_(const ContainerAllocator& _alloc)
    : age(0)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _age_type;
  _age_type age;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::beginner_tutorials::Person_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::Person_<ContainerAllocator> const> ConstPtr;

}; // struct Person_

typedef ::beginner_tutorials::Person_<std::allocator<void> > Person;

typedef boost::shared_ptr< ::beginner_tutorials::Person > PersonPtr;
typedef boost::shared_ptr< ::beginner_tutorials::Person const> PersonConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::Person_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::Person_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::Person_<ContainerAllocator1> & lhs, const ::beginner_tutorials::Person_<ContainerAllocator2> & rhs)
{
  return lhs.age == rhs.age &&
    lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::Person_<ContainerAllocator1> & lhs, const ::beginner_tutorials::Person_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::Person_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::Person_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::Person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::Person_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::Person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::Person_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "070ce487c3f77716520d1961df78fa95";
  }

  static const char* value(const ::beginner_tutorials::Person_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x070ce487c3f77716ULL;
  static const uint64_t static_value2 = 0x520d1961df78fa95ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/Person";
  }

  static const char* value(const ::beginner_tutorials::Person_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 age\n"
"string name\n"
;
  }

  static const char* value(const ::beginner_tutorials::Person_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::Person_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.age);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Person_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::Person_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::Person_<ContainerAllocator>& v)
  {
    s << indent << "age: ";
    Printer<int64_t>::stream(s, indent + "  ", v.age);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_PERSON_H
